# Generated by Django 5.1.1 on 2024-11-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(default=''),
        ),
    ]
