# Generated by Django 5.1.1 on 2024-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='ruta_imagen',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='ruta_imagen',
        ),
        migrations.AddField(
            model_name='comic',
            name='imagen',
            field=models.ImageField(default='null', upload_to='imagenes_comics', verbose_name='Imagen Comic'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='imagen',
            field=models.ImageField(default='null', upload_to='imagenes_trueque', verbose_name='Imagen Objeto o Servicio'),
        ),
    ]
