# Generated by Django 5.1.3 on 2024-11-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_comic_imagen_alter_oferta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
