# Generated by Django 5.1.1 on 2024-11-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_listadeseos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='emisor',
        ),
        migrations.AddField(
            model_name='oferta',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='mainapp.comic'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('comic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='mainapp.comic')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_recibidas', to='mainapp.usuario')),
                ('oferta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='mainapp.oferta')),
            ],
        ),
    ]
